student
std::string student::name
int student::number
float student::sum
std::vector<float> student::grades
bool student::isValidName(const std::string &new_name)
bool student::isValidGrade(const float grade)
student::student(const int num, const std::string &full_name)
References MIN_GRADES.
int student::getNumber()
Referenced by TestClass::check_setNumber, TestClass::check_try_catch_getNumber, TestClass::test_invalid_getNumber.
std::string student::getName()
Referenced by TestClass::check_getName, TestClass::check_setName.
int student::getNumberGrades()
Referenced by addNewGrade, TestClass::check_addNewGrade, TestClass::check_are_received_grades_the_same, TestClass::fill_with_random_grades, getAverageGrade, TestClass::test_invalid_addNewGrade, TestClass::test_valid_addNewGrade.
std::vector< float > student::getGrades()
Referenced by TestClass::check_are_received_grades_the_same.
void student::setNumber(int num)
Referenced by TestClass::check_setNumber.
void student::setName(const std::string &newName)
Referenced by TestClass::check_setName.
void student::addNewGrade(float grade)
References getNumberGrades, MAX_GRADES.
Referenced by TestClass::check_addNewGrade.
bool student::areGradesRecieved()
Referenced by getAverageGrade, getMaxGrade, getMinGrade.
float student::getAverageGrade()
References areGradesRecieved, getNumberGrades.
Referenced by TestClass::test_invalid_getAverageGrade, TestClass::test_valid_getAverageGrade.
float student::getMaxGrade()
References areGradesRecieved.
Referenced by TestClass::test_invalid_getMaxGrade, TestClass::test_valid_getMaxGrade.
float student::getMinGrade()
References areGradesRecieved.
Referenced by TestClass::test_invalid_getMinGrade, TestClass::test_valid_getMinGrade.