TestClass
std::string TestClass::name
int TestClass::number
float TestClass::sum
std::vector<float> TestClass::grades
TestClass::TestClass()
References MIN_GRADES.
void TestClass::test_getNumber()
Referenced by main.
void TestClass::test_valid_getNumber()
References TEST_CLASS_LARGE_NEGATIVE_INT, TEST_CLASS_LARGE_POSITIVE_INT, TEST_CLASS_NEGATIVE_INT, TEST_CLASS_NOT_THAT_LARGE_NEGATIVE_INT, TEST_CLASS_NOT_THAT_LARGE_POS_INT, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING, TEST_CLASS_VALID_STRING_DASH.
void TestClass::test_invalid_getNumber()
References student::getNumber, IS_TRUE, TEST_CLASS_CHAR_LETTER, TEST_CLASS_CHAR_NUMBER, TEST_CLASS_CHAR_SYMBOL, TEST_CLASS_INVALID_STRING, TEST_CLASS_LARGE_NEGATIVE_INT, TEST_CLASS_LARGE_POSITIVE_INT, TEST_CLASS_LONG_LONG_INT_NEGATIVE, TEST_CLASS_NEGATIVE_DOUBLE, TEST_CLASS_NEGATIVE_FLOAT, TEST_CLASS_NEGATIVE_INT, TEST_CLASS_NOT_THAT_LARGE_NEGATIVE_INT, TEST_CLASS_NOT_THAT_LARGE_POS_INT, TEST_CLASS_POSITIVE_DOUBLE, TEST_CLASS_POSITIVE_FLOAT, TEST_CLASS_POSITIVE_INT, TEST_CLASS_UNSIGNED_LONG_LONG_INT, TEST_CLASS_VALID_STRING.
void TestClass::check_try_catch_getNumber(const int num, const std::string &name)
References student::getNumber, IS_TRUE.
void TestClass::test_getName()
Referenced by main.
void TestClass::test_valid_getName()
References TEST_CLASS_CHAR_LETTER, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING, TEST_CLASS_VALID_STRING_DASH.
void TestClass::test_invalid_getName()
References TEST_CLASS_CHAR_NUMBER, TEST_CLASS_CHAR_SYMBOL, TEST_CLASS_INVALID_STRING, TEST_CLASS_POSITIVE_INT.
void TestClass::check_getName(const int number, const std::string &name)
References student::getName, IS_TRUE.
void TestClass::test_setNumber()
Referenced by main.
void TestClass::test_valid_setNumber()
References TEST_CLASS_LARGE_NEGATIVE_INT, TEST_CLASS_LARGE_POSITIVE_INT, TEST_CLASS_NEGATIVE_INT, TEST_CLASS_NOT_THAT_LARGE_NEGATIVE_INT, TEST_CLASS_NOT_THAT_LARGE_POS_INT, TEST_CLASS_POSITIVE_INT.
void TestClass::test_invalid_setNumber()
References TEST_CLASS_CHAR_LETTER, TEST_CLASS_CHAR_NUMBER, TEST_CLASS_CHAR_SYMBOL, TEST_CLASS_LONG_LONG_INT_NEGATIVE, TEST_CLASS_NEGATIVE_DOUBLE, TEST_CLASS_NEGATIVE_FLOAT, TEST_CLASS_POSITIVE_DOUBLE, TEST_CLASS_POSITIVE_FLOAT, TEST_CLASS_UNSIGNED_LONG_LONG_INT.
void TestClass::check_setNumber(const int new_number)
References student::getNumber, IS_TRUE, student::setNumber.
void TestClass::test_setName()
Referenced by main.
void TestClass::test_valid_setName()
References TEST_CLASS_CHAR_LETTER, TEST_CLASS_VALID_STRING, TEST_CLASS_VALID_STRING_DASH.
void TestClass::test_invalid_setName()
References TEST_CLASS_CHAR_NUMBER, TEST_CLASS_CHAR_SYMBOL, TEST_CLASS_INVALID_STRING.
void TestClass::check_setName(const std::string &new_name)
References student::getName, IS_TRUE, student::setName.
void TestClass::test_addNewGrade()
Referenced by main.
void TestClass::test_valid_addNewGrade()
References student::getNumberGrades, HIGHEST_GRADE, LOWEST_GRADE, MAX_GRADES, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::test_invalid_addNewGrade()
References student::getNumberGrades, HIGHEST_GRADE, LOWEST_GRADE, MAX_GRADES, TEST_CLASS_BIG_POSITIVE_FLOAT, TEST_CLASS_CHAR_LETTER, TEST_CLASS_CHAR_NUMBER, TEST_CLASS_CHAR_SYMBOL, TEST_CLASS_NEGATIVE_FLOAT, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::check_addNewGrade(student &test_student, const float grade)
References student::addNewGrade, student::getNumberGrades, IS_TRUE.
void TestClass::test_getAverageGrade()
Referenced by main.
void TestClass::test_valid_getAverageGrade()
References student::getAverageGrade, IS_TRUE, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::test_invalid_getAverageGrade()
References student::getAverageGrade, IS_TRUE, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
float TestClass::calculate_average(std::vector< float > &grades)
References HIGHEST_GRADE, LOWEST_GRADE.
void TestClass::test_getMinGrade()
Referenced by main.
void TestClass::test_valid_getMinGrade()
References student::getMinGrade, IS_TRUE, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::test_invalid_getMinGrade()
References student::getMinGrade, IS_TRUE, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::fill_with_random_grades(student &test_student)
References student::getNumberGrades, HIGHEST_GRADE, LOWEST_GRADE, MAX_GRADES.
void TestClass::test_getMaxGrade()
Referenced by main.
void TestClass::test_valid_getMaxGrade()
References student::getMaxGrade, IS_TRUE, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::test_invalid_getMaxGrade()
References student::getMaxGrade, IS_TRUE, TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::test_getGrades()
Referenced by main.
void TestClass::test_valid_getGrades()
References TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::test_invalid_getGrades()
References TEST_CLASS_POSITIVE_INT, TEST_CLASS_VALID_STRING.
void TestClass::check_are_received_grades_the_same(student &test_student, std::vector< float > &temp_grades)
References student::getGrades, student::getNumberGrades, IS_TRUE.